apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: dgozalo
    provider: github
    repository: golangtestawstest2
  name: dgozalo-golangtestawstest2
spec:
  description: Imported application for dgozalo/golangtestawstest2
  httpCloneURL: https://github.com/dgozalo/golangtestawstest2.git
  org: dgozalo
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: golangtestawstest2
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/dgozalo/golangtestawstest2.git
